name: Environments

on:
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        default: test
        required: false
        description: Environment name

defaults:
  run:
    shell: bash

jobs:
  print:
    runs-on: ubuntu-latest
    # ハイフン付きキーはブラケット記法で
    environment: ${{ inputs['environment-name'] }}

    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Print username
        run: echo "USERNAME is $USERNAME"

      - name: Print password parts
        run: |
          first=${PASSWORD:0:1}
          rest=${PASSWORD#?}
          echo "PASSWORD first char: $first, rest: $rest"
